name: CI

on:
  push:
    paths:
      - sdk/**

defaults:
  run:
    working-directory: sdk/

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["16", "18"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "{dir}={$(yarn config get cacheFolder)}" >> $GITHUB_OUTPUT

      - name: Cache node modules
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ matrix.version }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node.js ${{ matrix.version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Type check
        run: yarn type-check

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

  publish:
    runs-on: ubuntu-latest
    needs: checks
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Copy README for npm
        run: cp ../README.md .

      - name: Publish to npm
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
